### ISSUE TITLE
Throwing away datagram. REASON: unable to parse: fm_rails_failed_ui_logins:1|c|#

### ISSUE THREAD

**Issue by lzap** [Erbenos/pcp-statsd-c#13]
Hey,

it looks like datadog ruby library sends the following packet when a measurement has no labels:

    fm_rails_failed_ui_logins:1|c|#

This ends up with:

    Throwing away datagram. REASON: unable to parse: fm_rails_failed_ui_logins:1|c|#

**Comment by Erbenos** [comment]
Are you running against the latest version in PCP repo? Version in this repo is quite outdated.

**Comment by lzap** [comment]
Oh sure, missed the warning in the README :-) Cheers!

**Comment by Erbenos** [comment]
@lzap If you run into the related issue with the up to date version as well, please do assign a ticket to me so I can track it and fix it, this is an edge case which I don't remember exactly should or should not be allowed in the code itself. I ll see if I can get the dev environment running again and check for it myself too.

**Comment by lzap** [comment]
Thanks this turned to be an issue in the Ruby statsd library, so far so good. Soon the PMDA will go into wild production! Cheers.

**Comment by Erbenos** [comment]
Issue or not I believe relaxing the parser shouldn't hurt anyone. Thanks for letting me know.
